#ifndef _RUN_PROCESS_APPLICATION
#define _RUN_PROCESS_APPLICATION

#define IOCTL_CREATE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLOSE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define DRIVERNAME L"OSiSP_Labs_7_Driver"
#define CREATE_EVENT L"CreateEvent"
#define CLOSE_EVENT L"CloseEvent"

typedef struct _PROCESS_INFO{
    int pid;
    char processName[_MAX_FNAME];
} PROCESS_INFO,*PPROCESS_INFO;
#endif
